Add missing namespace creation for pomerium
The namespace for pomerium is not created during the walkthrough so running the command to create the tls secret fails.

``` bash
% kubectl create secret tls pomerium-tls-ca --namespace=pomerium \
--cert="$(mkcert -CAROOT)/rootCA.pem" --key="$(mkcert -CAROOT)/rootCA-key.pem"
error: failed to create secret namespaces "pomerium" not found
```
This PR adds the creation of the namespace before running the tls secret command.